import logging
import os
from typing import Dict, Union, List
from py_clob_client.clob_types import OrderArgs
from src.client import PolymarketClient
from src.kalshi_client import KalshiClient

logger = logging.getLogger(__name__)
class Engine:
    """Handles trade execution logic for the Trader bot.
    
    The Engine is responsible for processing trade signals, applying risk management
    guards, and executing orders in either Dry-Run or Live mode.
    """
    
    def __init__(self, client: Union[PolymarketClient, KalshiClient], balance: float = 1400.0):
        """Initializes the Engine with a client and starting balance.
        
        Args:
            client (Union[PolymarketClient, KalshiClient]): The authenticated client for trade execution.
            balance (float): The starting virtual balance for Dry-Run mode. Defaults to 1400.0.
        """
        self.client = client
        self.balance = balance
        self.trades_executed = 0
        self.total_profit = 0.0
        self.is_kalshi = isinstance(client, KalshiClient)
        
        # Safety Guards from Environment
        self.live_mode = os.getenv("LIVE_MODE", "false").lower() == "true"
        self.max_trade_usd = float(os.getenv("TRADE_LIMIT_USD", "10.0"))
        self.max_slippage = float(os.getenv("SLIPPAGE_TOLERANCE", "0.01"))

    async def execute_trade(self, signal: Dict):
        """Processes a trade signal and coordinates execution based on the current mode.
        
        Args:
            signal (dict): The inefficiency data generated by the Scanner.
        """
        market_question = signal.get("question")
        total_price = signal.get("total_price")
        
        # 1. Verification & Risk Check
        potential_profit_pct = (1.0 / total_price) - 1.0
        trade_amount = min(self.balance * 0.10, self.max_trade_usd)
        
        if trade_amount <= 0:
            logger.error("Trade amount is zero or negative. Skipping.")
            return

        # 2. Execution logic
        if self.is_kalshi:
            if self.live_mode:
                await self._execute_kalshi_live_trade(signal, trade_amount)
            else:
                self._execute_dry_run(signal, trade_amount, potential_profit_pct)
        else:
            if self.live_mode:
                await self._execute_poly_live_trade(signal, trade_amount)
            else:
                self._execute_dry_run(signal, trade_amount, potential_profit_pct)

    def _execute_dry_run(self, signal: Dict, trade_amount: float, profit_pct: float):
        """Simulates a trade execution and updates virtual tracking."""
        profit = trade_amount * profit_pct
        self.balance += profit
        self.total_profit += profit
        self.trades_executed += 1
        
        source = signal.get("source", "unknown")
        logger.info(f"--- [DRY-RUN] ({source.upper()}) TRADE EXECUTED ---")
        logger.info(f"Market: {signal['question']}")
        logger.info(f"Total Price: ${signal['total_price']:.4f}")
        logger.info(f"Profit: ${profit:.2f}")
        logger.info(f"New Balance: ${self.balance:.2f}")

    async def _execute_poly_live_trade(self, signal: Dict, trade_amount: float):
        """Coordinates live order placement on the Polymarket CLOB."""
        logger.warning(f"!!! [LIVE] (Poly) INITIATING ARBITRAGE for: {signal['question']} !!!")
        
        tokens = signal.get("tokens") # [YES_TOKEN, NO_TOKEN]
        prices = signal.get("best_asks") # [YES_PRICE, NO_PRICE]
        
        try:
            total_unit_price = sum(prices)
            share_count = trade_amount / total_unit_price
            
            for i, token_id in enumerate(tokens):
                order_args = OrderArgs(
                    price=prices[i],
                    size=round(share_count, 2),
                    side="BUY",
                    token_id=token_id
                )
                await self.client.post_order(order_args)

            self.trades_executed += 1
            logger.warning("!!! [LIVE] (Poly) ARBITRAGE ORDERS PLACED SUCCESSFULLY !!!")
        except Exception as e:
            logger.error(f"Poly live trade failure: {e}")

    async def _execute_kalshi_live_trade(self, signal: Dict, trade_amount: float):
        """Coordinates live order placement on Kalshi."""
        logger.warning(f"!!! [LIVE] (Kalshi) INITIATING ARBITRAGE for: {signal['question']} !!!")
        
        ticker = signal.get("ticker")
        prices = signal.get("best_asks") # [YES_PRICE_CENTS, NO_PRICE_CENTS]
        
        try:
            # On Kalshi, buying 1 contract of YES and 1 contract of NO usually locks in $1.
            # share_count is based on contracts. Each contract is effectively $1 max.
            total_unit_cost_cents = sum(prices)
            contract_count = int((trade_amount * 100) / total_unit_cost_cents)
            
            if contract_count < 1:
                return

            # Place YES order
            self.client.post_order(ticker, side="yes", action="buy", count=contract_count, price=prices[0])
            # Place NO order
            self.client.post_order(ticker, side="no", action="buy", count=contract_count, price=prices[1])

            self.trades_executed += 1
            logger.warning("!!! [LIVE] (Kalshi) ARBITRAGE ORDERS PLACED SUCCESSFULLY !!!")
            
        except Exception as e:
            logger.error(f"Kalshi live trade failure: {e}")
