import logging
import os
from typing import Dict
from src.kalshi_client import KalshiClient

logger = logging.getLogger(__name__)


class Engine:
    """Handles trade execution logic for the Trader bot.

    The Engine is responsible for processing trade signals, applying risk management
    guards, and executing orders in either Dry-Run or Live mode.
    """

    def __init__(self, client: KalshiClient, balance: float = 1400.0):
        """Initializes the Engine with a client and starting balance.

        Args:
            client (KalshiClient): The authenticated client for trade execution.
            balance (float): The starting virtual balance for Dry-Run mode. Defaults to 1400.0.
        """
        self.client = client
        self.balance = balance
        self.trades_executed = 0
        self.total_profit = 0.0
        self.is_kalshi = True

        # Safety Guards from Environment
        self.live_mode = os.getenv("LIVE_MODE", "false").lower() == "true"
        self.max_trade_usd = float(os.getenv("TRADE_LIMIT_USD", "10.0"))
        self.max_slippage = float(os.getenv("SLIPPAGE_TOLERANCE", "0.01"))

    async def execute_trade(self, signal: Dict):
        """Processes a trade signal and coordinates execution based on the current mode.

        Args:
            signal (dict): The inefficiency data generated by the Scanner.
        """
        total_price = signal.get("total_price")

        # 1. Verification & Risk Check
        potential_profit_pct = (1.0 / total_price) - 1.0
        trade_amount = min(self.balance * 0.10, self.max_trade_usd)

        logger.info(
            f"Checking trade: Amount=${trade_amount:.2f} | Balance=${self.balance:.2f} | Potential Profit={potential_profit_pct:.2%}"
        )

        if trade_amount <= 0:
            logger.warning(
                f"Trade amount is zero (Balance: ${self.balance:.2f}). Skipping."
            )
            return

        # 2. Execution logic
        if self.live_mode:
            await self._execute_kalshi_live_trade(signal, trade_amount)
        else:
            self._execute_dry_run(signal, trade_amount, potential_profit_pct)

    def _execute_dry_run(
        self, signal: Dict, trade_amount: float, profit_pct: float
    ) -> None:
        """Simulate a trade execution for tracking in non-live mode.

        Args:
            signal (dict): The inefficiency data generated by the Scanner.
            trade_amount (float): The amount of virtual USD to allocate.
            profit_pct (float): The expected percentage return.
        """
        profit = trade_amount * profit_pct
        self.balance += profit
        self.total_profit += profit
        self.trades_executed += 1

        logger.info("--- [DRY-RUN] (KALSHI) TRADE EXECUTED ---")
        logger.info(f"Market: {signal['question']}")
        logger.info(f"Total Price: ${signal['total_price']:.4f}")
        logger.info(f"Profit: ${profit:.2f}")
        logger.info(f"New Balance: ${self.balance:.2f}")

    async def _execute_kalshi_live_trade(self, signal: Dict, trade_amount: float) -> None:
        """Execute simultaneous YES and NO limit orders on Kalshi for arbitrage.

        Args:
            signal (dict): Market data including ticker and current best asks (in cents).
            trade_amount (float): Total USD budget for this specific trade.
        """
        logger.warning(
            f"!!! [LIVE] (Kalshi) INITIATING ARBITRAGE for: {signal['question']} !!!"
        )

        ticker = signal.get("ticker")
        prices = signal.get("best_asks")  # [IMPLIED_YES_ASK, IMPLIED_NO_ASK]

        try:
            # On Kalshi, buying 1 contract of YES and 1 contract of NO usually locks in $1.
            total_unit_cost_cents = sum(prices)
            contract_count = int((trade_amount * 100) / total_unit_cost_cents)

            logger.info(
                f"Calculating contracts: Budget=${trade_amount:.2f} | Implied Total Cost={total_unit_cost_cents}c | Contracts={contract_count}"
            )

            if contract_count < 1:
                logger.warning(
                    f"Contract count is < 1 for ticker {ticker}. Budget too low or price too high."
                )
                return

            # Place YES order
            logger.info(
                f"Placing YES order: ticker={ticker}, count={contract_count}, price={prices[0]}c (Hitting Implied Ask)"
            )
            self.client.post_order(
                ticker, side="yes", action="buy", count=contract_count, price=prices[0]
            )
            # Place NO order
            logger.info(
                f"Placing NO order: ticker={ticker}, count={contract_count}, price={prices[1]}c (Hitting Implied Ask)"
            )
            self.client.post_order(
                ticker, side="no", action="buy", count=contract_count, price=prices[1]
            )

            self.trades_executed += 1
            logger.warning(
                "!!! [LIVE] (Kalshi) ARBITRAGE ORDERS PLACED SUCCESSFULLY !!!"
            )

        except Exception as e:
            logger.error(f"Kalshi live trade failure: {e}")
            raise
